
@host=https://kasamatsu.atlassian.net/
@apipath=rest/api/3/search
@ApiPathIssueFields=rest/api/3/field

@jql=project = todo AND status = "To Do"
@startAt=0
@maxResults=10
@fields=summary,description
@expand=changelog
@request_path=?jql={{jql}}&startAt={{startAt}}&maxResults={{maxResults}}&fields={{fields}}&expand={{expand}}


### JIRAデータの取得
GET {{host}}{{apipath}}{{request_path}} HTTP/1.1
content-type: application/json
Authorization: Basic {{JIRA_USERNAME}}:{{JIRA_API_TOKEN}}


### フィールド一覧取得
GET {{host}}{{ApiPathIssueFields}} HTTP/1.1
content-type: application/json
Authorization: Basic {{JIRA_USERNAME}}:{{JIRA_API_TOKEN}}